apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  template:
    spec:
      containers:
      - name: minio
        image: minio/minio
        ports:
        - containerPort: 9001
          hostPort: 9001
        args: 
        - server
        - --address
        - :9000
        - --console-address 
        - :9001
        - /storage