apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio
commonLabels:
  app: minio
  
resources:
- deployment.yaml
- namespace.yaml
- service.yaml

replicas:
- name: minio
  count: 1
